Update patch set 1
Patch Set 1:

Is this really all that's needed?  I see changes to several files besides this one.

https://gist.github.com/496bc46e8ae2522c78dd

And then there's a 

 error: 'EFFECT_CMD_CONFIGURE' was not declared in this scope

That I'm seeing for a few of the files as well.

Patch-set: 1